# Site settings
title: Portf칩lio de an치lises
email: juan.satyro@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Portf칩lio de an치lises criadas para a disciplina de AD1
url: "https://JuanAlmeida12.github.io/analises-pf/" # the base hostname & protocol for your site
github_username:  JuanAlmeida12
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
